name: ruby_robbery
description: Steal the ruby. All the rubies.

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: 2.8.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^0.23.0+1
  gap: ^2.0.0
  google_fonts: ^2.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  package_info_plus: ^1.3.0
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.1
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/audio/
