name: ruby_theft
description: Steal the ruby. All the rubies.

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: 2.8.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.1
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
